### ISSUE TITLE
An issue about a  imported css file

### ISSUE THREAD

**Issue by fengtaijun0507** [jekyller/vitae#1]
I saw a bug  on the browser console ! The following is :
  " Mixed Content: The page at 'https://biomadeira.github.io/vitae/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Raleway:700,400'. This request has been blocked; the content must be served over HTTPS."

**Comment by biomadeira** [comment]
@fengtaijun0507 https://fonts.googleapis.com/css?family=Raleway:700,400 works just as fine.
Just change the url address to https. I will commit that change soon too.

Thanks for noticing!

**Comment by fengtaijun0507** [comment]
Pleasure!
